development:
  bucket_name: demo_bucket
  access_key_id: secret
  secret_access_key: super_secret
  max_file_size: 10485760
       
test:
  bucket_name: test_bucket
  access_key_id: 
  secret_access_key: 
  max_file_size: 1048576
  
production:
  bucket_name: production_bucket
  access_key_id: 
  secret_access_key: 
  max_file_size: 1048576